### ISSUE TITLE
PlatformException while attempting to Authorize App 

### ISSUE THREAD

**Issue by bryanbill** [twitter-dart/twitter-oauth2-pkce#15]
# 1. Current bug behavior

While attempting to authorize the Twitter app, PlatformException(CANCELED) is thrown even though all the required credentials are provided.

# 2. Expected behavior

On successful authorization, the user should be rerouted to the app with the resulting query parameters.

# 3. Steps to reproduce

Run the example folder with the environment provided below.

# 4. Flutter doctor output

```terminal
 Flutter (Channel stable, 3.0.3, on Ubuntu 22.04 LTS 5.15.0-40-generic,
    locale en_GB.UTF-8)
    • Flutter version 3.0.3 at /home/paperback/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (11 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/paperback/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /home/paperback/dev/android/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/paperback/dev/android
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • 2201117SG (mobile) • M7U8R87H9LHQ756P • android-arm64  • Android 11 (API
      30)
    • Linux (desktop)    • linux            • linux-x64      • Ubuntu 22.04 LTS
      5.15.0-40-generic
    • Chrome (web)       • chrome           • web-javascript • Google Chrome
      103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

# 5. More environment information
- twitter_oauth2_pkce version: 0.4.0

# 6. More information

The underlying cause may be due to a bug in flutter_web_auth, is there a possible alternative to it?

**Comment by myConsciousness** [comment]
Hi @bryanbill , thanks for your feedback!

Which specific platforms have you tried? I have checked that it works fine on Android and iOS with example codes at least.

**Comment by bryanbill** [comment]
Hello @myConsciousness, I tried running the example app on Android 11 and 10 devices, and both failed with the aforementioned exception. I haven't got a chance to test with an iPhone yet.

**Comment by myConsciousness** [comment]
@bryanbill 

Let me ask you a few questions to help me understand the situation :)

- Setting `org.example.android.oauth://callback/` in Twitter Developer as a callback url like example?
- Added definitions to `AndroidManifest.xml`?
- Is the emulator you are using created with `Android Studio`?
    - Because this emulator does not work correctly. 
    - https://github.com/google/android-emulator-m1-preview

**Comment by bryanbill** [comment]
> @bryanbill
> 
> Let me ask you a few questions to help me understand the situation :)
> 
> * Setting `org.example.android.oauth://callback/` in Twitter Developer as a callback url like example?
> * Added definitions to `AndroidManifest.xml`?
> * Is the emulator you are using created with `Android Studio`?
>   
>   * Because this emulator does not work correctly.
>   * https://github.com/google/android-emulator-m1-preview

* Callback URL Set on Twitter Dev as in the example. ✅
* Defined the required scheme in Android Manifest ✅
* I'm running  on a physical device ✅

**Comment by bryanbill** [comment]
To add more context, the user is authorized and the session can be viewed under "Apps and Sessions" on the Twitter App. Seems like something happens during the callback triggering the PlatformException(CANCELED. User canceled login, null, null)

**Comment by bryanbill** [comment]
@myConsciousness I finally solved it, everything is working as supposed. I was omitting the last bit (.oauth) in my scheme.

What I had before: 
```dart
... scheme = "org.example.android";
```

What I should have had:
```dart
... scheme = "org.example.android.oauth";
```

Lemme close this. Thanks for helping out.

**Comment by novas1r1** [comment]
Hey @bryanbill,
actually I have the correct scheme set but I still cant make it work.

Any other hint what could go wrong? It is working fine with the example code. I have checked all possible differences and copy pasted them over. It is working fine for ios, but no success on Android. Still getting this error where the twitter page comes up and then when I click on authorize its loading infinitly and not closing. Sometimes its closing but coming up again. Endless loop...

**Comment by myConsciousness** [comment]
Hi @novas1r1 :)

If this is an Android-specific event, it is possible that the AndroidManifest.xml settings are incorrect. You already tried example of this repository like below?

https://github.com/twitter-dart/twitter-oauth2-pkce#1131-android

**Comment by novas1r1** [comment]
Hi @myConsciousness,
thanks for the fast response! I did put it exactly like its in the example. I also implemented the button exactly like in the example, just replaced Twitter credentials. Still no sucess :(! I guess it's something project related then... could it be some other deeplink interfeering? I'm a little lost, spent like 10 hours on this already.

**Comment by myConsciousness** [comment]
Hi @novas1r1 ,

This is the difficulty of OAuth 2.0 PKCE in Flutter, I also wasted so many wasted hours on technical validation when creating this library haha.

Can you share any information you have set up, logs of errors, etc., if possible? I assume from the fact that it works on iOS that the credentials settings seem to be correct.

Or maybe this is a bug in [flutter_web_auth](https://github.com/LinusU/flutter_web_auth/issues), and this library honestly only prepares the user before authentication and verifies the user after authentication.

**Comment by novas1r1** [comment]
Hey there,
This library would definitely a life saver if the redirect can be fixed somehow. I would love to give you more information on that, but I tried copy pasting stuff over and I couldn't figure out what breaks it. Maybe it's related to flavors? Maybe another deeplink implementation is interfering... I will try to reproduce it somehow and report back as soon as I have any hint on that.

For now I fixed it using the oauth1 flow with twitter_login package and fetching data using a twitter-api-v2 package. Redirect works fine, but well, it's oauth1. Nothing which will stay there forever.

I will dig a little deeper and inform you if anything related to that issue can be reproduced.

Thanks for your help and the package ❤️

**Comment by collo54** [comment]
Same issue. I followed all steps but I keep getting the platform exception error.

**Comment by collo54** [comment]
OAuth 1 it is

**Comment by bryanbill** [comment]
Well, reopening this.

Authentication works only on some devices but fails on others.
@myConsciousness can I give this issue a shot? Lemme see if I can fix it

**Comment by bryanbill** [comment]
> Hey there, This library would definitely a life saver if the redirect can be fixed somehow. I would love to give you more information on that, but I tried copy pasting stuff over and I couldn't figure out what breaks it. Maybe it's related to flavors? Maybe another deeplink implementation is interfering... I will try to reproduce it somehow and report back as soon as I have any hint on that.
> 
> For now I fixed it using the oauth1 flow with twitter_login package and fetching data using a twitter-api-v2 package. Redirect works fine, but well, it's oauth1. Nothing which will stay there forever.
> 
> I will dig a little deeper and inform you if anything related to that issue can be reproduced.
> 
> Thanks for your help and the package heart

Hello @novas1r1, any update on this? I would like to chip in.

**Comment by myConsciousness** [comment]
Hi @bryanbill , thanks for your feedback :)

I heard @novas1r1 started to use OAuth 1.0a instead of OAuth 2.0 PKCE, and I guess she don't try this for now. 

And I'm not actively investigating this, but the fact that it behaves differently on different devices makes me think it's a bug in `flutter_web_auth`. This is because the redirection is not actively handled by this library, but depends on the functionality of `flutter_web_auth`.

However, if this issue is unique to this library, it would be significant to resolve. The process of redirection in this library is as follows :)

https://github.com/twitter-dart/twitter-oauth2-pkce/blob/53aeae4271b10d8ac967576b7685eda0eff61266/lib/src/twitter_oauth2_client.dart#L104-L142

https://github.com/twitter-dart/twitter-oauth2-pkce/blob/53aeae4271b10d8ac967576b7685eda0eff61266/lib/src/auth/io_web_auth.dart#L13-L24

**Comment by bryanbill** [comment]
> Hi @bryanbill , thanks for your feedback :)
> 
> I heard @novas1r1 started to use OAuth 1.0a instead of OAuth 2.0 PKCE, and I guess she don't try this for now.
> 
> And I'm not actively investigating this, but the fact that it behaves differently on different devices makes me think it's a bug in `flutter_web_auth`. This is because the redirection is not actively handled by this library, but depends on the functionality of `flutter_web_auth`.
> 
> However, if this issue is unique to this library, it would be significant to resolve. The process of redirection in this library is as follows :)
> 
> https://github.com/twitter-dart/twitter-oauth2-pkce/blob/53aeae4271b10d8ac967576b7685eda0eff61266/lib/src/twitter_oauth2_client.dart#L104-L142
> 
> https://github.com/twitter-dart/twitter-oauth2-pkce/blob/53aeae4271b10d8ac967576b7685eda0eff61266/lib/src/auth/io_web_auth.dart#L13-L24

Seems like the issue is on flutter_web_auth. See this [issue](https://github.com/LinusU/flutter_web_auth/issues/134)
